run:
  timeout: 5m
  modules-download-mode: readonly

output:
  sort-results: true
  print-issued-lines: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - goimports
    - govet
    - staticcheck
    - revive
  
linters-settings:
  govev:
    enable:
      - niliness
      - reflectvaluecompare
      - sortslice
      - unusedwrite

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0